# Copyright (c) 2015-2016, Maciej Sieczka, Gregory M. Kurtzer. All rights
# reserved.
#
# Copyright (c) 2020, S. Alexander. All rights reserved.
#
# Copyright (c) 2017-2018, SyLabs, Inc. All rights reserved.
# Copyright (c) 2017, SingularityWare, LLC. All rights reserved.
#
# Copyright (c) 2015-2017, Gregory M. Kurtzer. All rights reserved.
#
# Minimal installation process is defined in
# libexec/bootstrap/modules-v2/dist-arch.sh. A couple extra actions are called
# from here in `%post' section. Adjust them as needed.
# https://wiki.archlinux.org/index.php/Installation_Guide may come in handy.

Bootstrap: docker
From: archlinux

%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"

    # Set time zone. Use whatever you prefer instead of UTC.
    ln -s /usr/share/zoneinfo/UTC /etc/localtime

    # Set locale. Use whatever you prefer instead of en_US.
    echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    # Add more locales as needed, eg:
    # echo 'de_DE.UTF-8 UTF-8' >> /etc/locale.gen
    locale-gen
    echo 'LANG=en_US.UTF-8' > /etc/locale.conf
    # Mind that Singularity's shell will use host's locale no matter what
    # anyway, as of version 2.1.2. This may change in a future release.

    # Set the package mirror server(s). This is only for the output image's
    # mirrorlist. `pacstrap' can only use your hosts's package mirrors.
    echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    # Add any number of fail-over servers, eg:
    echo 'Server = https://archlinux.honkgong.info/$repo/os/$arch' >> /etc/pacman.d/mirrorlist

    # Need pikaur to install from AUR as root
    pacman -Sy --noconfirm sudo git fakeroot binutils make
    echo "nobody ${HOSTNAME}= NOPASSWD: /usr/bin/halt,/usr/bin/poweroff,/usr/bin/reboot,/usr/bin/pacman" >> /etc/sudoers
    git clone https://aur.archlinux.org/pikaur.git /tmp/pikaur
    chgrp nobody /tmp/pikaur
    chmod g+ws /tmp/pikaur
    setfacl -m u::rwx,g::rwx /tmp/pikaur
    setfacl -d --set u::rwx,g::rwx,o::- /tmp/pikaur
    cd /tmp/pikaur
    sudo -u nobody makepkg -si --noconfirm
    sed -i "/^nobody ${HOSTNAME}= NOPASSWD: .*$/d" /etc/sudoers
    rm -r /tmp/pikaur 

    # Remove the packages downloaded to image's Pacman cache dir.
    pacman -Sy --noconfirm pacman-contrib
    paccache -r -k0
